---
abstract: 'Wrapper Around czmq high level ZMQ API'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
  ExtUtils::ParseXS: 3.18
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ZMQ-LibCZMQ1
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  XSLoader: 0.02
  ZMQ::Constants: 0
resources:
  bugtracker: https://github.com/lestrrat/p5-ZMQ/issues
  homepage: https://github.com/lestrrat/p5-ZMQ
  repository: git://github.com/lestrrat/p5-ZMQ.git
version: '0.04'
